### ISSUE TITLE
tcnative doesn't load in windows 64

### ISSUE THREAD

**Issue by alexlehm** [netty/netty-tcnative#187] opened 2016-09-06 16:26 UTC
When using tcnative in windows64, I get a dll load error regardless of the version used. From the error message I would guess that the file is created in %TEMP% and the file is left open, which locks the file so that it cannot be loaded as dll.

I am currently using netty-tcnative-boringssl-static 1.1.33.Fork22 windows-x86_64, the same error shows when using the openssl dynamic version

````
2016-09-06 18:19:19.576 DEBUG [main] io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable:169 - Unable to load the library: netty-tcnative.
java.lang.UnsatisfiedLinkError: C:\Users\alex\AppData\Local\Temp\netty-tcnative9215275112754372390.dll: The process cannot access the file because it is being used by another process
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:245)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:216)
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:166)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:380)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:99)
	at cx.lehmann.vertx.SSLHelperTest.testUseOpenSSLCiphersWhenNotSpecified(SSLHelperTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
````

**Comment by normanmaurer** [comment] 2016-09-06 16:52
@alexlehm duplicate of https://github.com/netty/netty/pull/5776

**Closed by normanmaurer** 2016-09-06 16:52 UTC

**Comment by alexlehm** [comment] 2016-09-06 18:40
thank you, I missed that since I only looked in the tcnative issue tracker
when changing the version to 4.1.6-snapshot, it works again.
