### ISSUE TITLE
Memory leak on SslProvider instantiation with netty-tcnative-boringssl-static

### ISSUE THREAD

**Issue by notdryft** [netty/netty-tcnative#788] opened 2023-05-04 13:28 UTC
We observed a memory leak that happens by switching from `netty-tcnative-boringssl-static` version `2.0.56.Final` to `2.0.57.Final` (or later, we tested up to `2.0.60.Final`).

Scenario is as follow:

* Create a `SslContextBuilder` once

```java
SslContextBuilder sslContextBuilder = SslContextBuilder.forClient.sslProvider(SslProvider.OPENSSL_REFCNT)
sslContextBuilder.ciphers(null, IdentityCipherSuiteFilter.INSTANCE_DEFAULTING_TO_SUPPORTED_CIPHERS)
```

For us the issue happened with both `SslProvider.OPENSSL_REFCNT` and `SslProvider.OPENSSL`.

Then, inside a loop:

* `SslContext sslContext = sslContextBuilder.build()`
* `ReferenceCountUtil.release(sslContext)`

Do that millions of times and you can see the following happen, left is `2.0.56.Final` and after the memory drop, `2.0.57.Final`:

<img width="721" alt="Screenshot 2023-05-04 at 15 12 10" src="https://user-images.githubusercontent.com/2608594/236214755-9473dc61-9745-4c07-a908-ce230e77aa19.png">

In our test case, `-Xms` and `-Xmx` were both `1G` so memory shouldn't be expected to grow that much more as everything is recycled right after instantiation.

Sample project that reproduces the issue provided as an attachment: [test-netty-tcnative-leak.zip](https://github.com/netty/netty-tcnative/files/11397904/test-netty-tcnative-leak.zip)

Command to run the project: `mvn compile exec:java -Dexec.mainClass=Main`

**Comment by notdryft** [comment] 2023-05-04 13:33
Forgot to mention something. When trying to pin down the issue, we used `-Dio.netty.leakDetection.level=paranoid` but it printed nothing!

**Comment by slandelle** [comment] 2023-05-04 14:35
Caused by #759 ?

**Comment by normanmaurer** [comment] 2023-05-04 14:43
Please upgrade to 2.0.60.Final Am 04.05.2023 um 16:35 schrieb Stephane Landelle ***@***.***>:﻿
Caused by #759 ?

**Comment by slandelle** [comment] 2023-05-04 14:46
@normanmaurer 

> or later, we tested up to 2.0.60.Final

Included. 2.0.60 included is the version we currently have in production and it suffers from the same issue. We were able to figure out the regression was introduced in  2.0.57.

**Comment by slandelle** [comment] 2023-05-04 14:50
Context: for Gatling's most common use case, we want to have distinct SSLContexts per virtual users some we generate the proper number of handshakes and SSLSessions. The leak goes probably unnoticed for the more standard use case of having one static SSLContext per client application.

**Comment by normanmaurer** [comment] 2023-05-04 15:36
Got it... will have a look

**Comment by slandelle** [comment] 2023-05-04 15:49
Thanks a lot! 🙇

**Comment by normanmaurer** [comment] 2023-05-05 08:48
Should be fixed by https://github.com/netty/netty-tcnative/pull/790 🤦

**Closed** 2023-05-05 10:06 UTC

**Comment by notdryft** [comment] 2023-05-05 10:46
Can still observe a leak after the fix:

<img width="717" alt="Screenshot 2023-05-05 at 12 44 52" src="https://user-images.githubusercontent.com/2608594/236438056-6afe5b7d-2f14-4bcd-a102-d3fc4eb29bde.png">

Not sure if it's because I compiled the fix branch badly or because there is more to the actual fix... will continue digging.

**Comment by normanmaurer** [comment] 2023-05-05 10:57
Are you sure you changed the dependency to point tot the snapshot and add the classifier ?Am 05.05.2023 um 12:46 schrieb Guillaume Corré ***@***.***>:﻿
Can still observe a leak after the fix:

Not sure if it's because I compiled the fix branch badly or because there is more to the actual fix... will continue digging.

**Comment by notdryft** [comment] 2023-05-05 11:00
Actually had clashing lib loading paths. Compiling again and confirming soon!

**Comment by notdryft** [comment] 2023-05-05 11:25
Confirming it was a path clash, everything looks good on 10M iterations:

<img width="726" alt="Screenshot 2023-05-05 at 13 19 06" src="https://user-images.githubusercontent.com/2608594/236444346-4ee289c7-9c7a-4fbb-ba37-880616d668c4.png">

`calloc` was also present in async-profiler's nativemem mode (built from the malloc branch in their own repo) before the fix. It's now all gone 🎉

**Comment by franz1981** [comment] 2023-05-05 11:47
Many thanks for double checking @notdryft
