### ISSUE TITLE
Compatibility Matrix

### ISSUE THREAD

**Issue by floragunncom** [netty/netty-tcnative#271] opened 2017-05-16 14:20 UTC
Ist there a matrix (or other kind of documentation) where i can see which tcnative version is compatible with which netty version?

**Comment by Scottmitch** [comment] 2017-05-17 21:08
Duplicate of https://github.com/netty/netty/issues/4808. Currently there is nothing but lets continue the discussion there. We have considered moving the netty-tcnative project into the netty project which would alleviate version mismatch ambiguities, but have not fully investigated the feasibility of this approach yet.

**Closed by Scottmitch** 2017-05-17 21:08 UTC
