### ISSUE TITLE
netty-tcnative-boringssl-static fails to load after version 2.0.48

### ISSUE THREAD

**Issue by spencejackson** [netty/netty-tcnative#716] opened 2022-03-24 17:47 UTC
Starting in 2.0.49, I am seeing:

OpenSsl.isAvailable() returns false

OpenSsl.unavailabilityCause() returns
[io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:114), io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:705), io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:146), io.baffle.shield.sql.mysql.BaffleShield.run(BaffleShield.java:349)]

**Comment by temawi** [comment] 2022-03-30 17:54
I have also been impacted by this while [trying to upgrade grpc-java to the latest netty](https://github.com/grpc/grpc-java/pull/9027). It looks like since netty-tcnative-boringssl-static 2.0.49 the jar no longer contains the native libraries and at least Gradle and Bazel are having a hard time including the dependent libraries that now have them. 

In our Gradle build I was able to work around this by including all the individual libraries (e.g. "io.netty:netty-tcnative-boringssl-static:2.0.51.Final:linux-x86_64") excplicitly.

Bazel does not seem to like this approach though and reports a cyclical dependency:

ERROR: /[tmpfs/tmp/bazel/external/maven/BUILD:548](https://cs.corp.google.com/piper///depot/google3/tmpfs/tmp/bazel/external/maven/BUILD?l=548):11: in jvm_import rule @maven//:io_netty_netty_tcnative_boringssl_static_osx_aarch_64: cycle in dependency graph:
    //netty/shaded:shaded
    @io_netty_netty_tcnative_boringssl_static_linux_x86_64//jar:jar
    @maven//:io_netty_netty_tcnative_boringssl_static_linux_x86_64
.-> @maven//:io_netty_netty_tcnative_boringssl_static_osx_aarch_64
|   @maven//:io_netty_netty_tcnative_boringssl_static_linux_aarch_64
`-- @maven//:io_netty_netty_tcnative_boringssl_static_osx_aarch_64

@ejona86

**Comment by spencejackson** [comment] 2022-03-30 23:00
Yes, I'm using Gradle.

**Comment by fedorka** [comment] 2022-03-31 15:48
We're also using Gradle and are impacted by the change. We were packaging the uber-jar as part of our platform IPC libraries so we can support both our deployed servers and the wide variety of developer environments.

**Comment by sannam888** [comment] 2022-04-03 11:32
@ejona86 I doubt that the problem is related to Gradle. From what I can see, the netty-tcnative-boringssl-static uber jar which used to contain the native libraries for all the platforms is now empty! Hence anyone depending on the uber jar will now fail to load the native library.
The most likely commit that broke this is: https://github.com/netty/netty-tcnative/commit/6fb5b01208671c007ad7f752e51ccc8b25dfca2f

**Comment by spencejackson** [comment] 2022-04-04 14:24
I agree. After 2.0.48 the size of the jar takes a nosedive.

> @ejona86 I doubt that the problem is related to Gradle. From what I can see, the netty-tcnative-boringssl-static uber jar which used to contain the native libraries for all the platforms is now empty! Hence anyone depending on the uber jar will now fail to load the native library.
> 
> The most likely commit that broke this is: [6fb5b01](https://github.com/netty/netty-tcnative/commit/6fb5b01208671c007ad7f752e51ccc8b25dfca2f)
> 
> Note that libraries that depend on netty-tcnative-boringssl-static (eg. Spring) have dependencies on the uber jar because they don't know what platform their users are going to be on.

**Comment by ejona86** [comment] 2022-04-04 14:27
> From what I can see, the netty-tcnative-boringssl-static uber jar which used to contain the native libraries for all the platforms is now empty!

But the pom now depends on the various platform-specific classifiers. So the other binaries are getting brought it from the dependency system. It seems it was likely tested with Maven and got working, but Gradle behaves differently.

**Comment by Zetten** [comment] 2022-04-04 15:13
I think a related issue is being thrown up by 6da7a219d48f039d1b3c7076d0adee193f6c12f7 (included in `io.netty:netty-tcnative-boringssl-static:2.0.51.Final`) which changes the `Automatic-Module-Name` in the manifest of the former uberjar, and hardcodes it to `osx-x86_64`:

```
$ curl -sL https://repo.maven.apache.org/maven2/io/netty/netty-tcnative-boringssl-static/2.0.51.Final/netty-tcnative-boringssl-static-2.0.51.Final.jar | zcat -q - | grep Automatic-Module-Name
Automatic-Module-Name: io.netty.tcnative.openssl.osx-x86_64
```

This is causing problems in my bazel build where javac is failing to handle this transitive dep on the classpath:

```Building resource/libazure-blob-resource.jar (3 source files) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 17 arguments skipped)
error: cannot determine module name for bazel-out/k8-fastbuild/bin/external/maven/v1/https/repo.maven.apache.org/maven2/io/netty/netty-tcnative-boringssl-static/2.0.51.Final/header_netty-tcnative-boringssl-static-2.0.51.Final.jar
```

**Comment by ejona86** [comment] 2022-04-04 15:31
@Zetten, yes, we saw that issue as well, but there was already some discussion about that. @temawi, might have a link. When we semi-worked around this issue Java 11 execution failed but Java 8 was okay. But it seems they are two separate issues.

**Comment by liuchong** [comment] 2022-04-19 15:12
Same issue here in clojure app build with leiningen:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.reflect.Method.copy(Method.java:161)
	at java.base/java.lang.reflect.ReflectAccess.copyMethod(ReflectAccess.java:102)
	at java.base/jdk.internal.reflect.ReflectionFactory.copyMethod(ReflectionFactory.java:309)
	at java.base/java.lang.Class.copyMethods(Class.java:3627)
	at java.base/java.lang.Class.getMethods(Class.java:2019)
	at clojure.lang.Reflector.getMethods(Reflector.java:498)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:436)
	at leiningen.core.pedantic$all_paths$iter__6753__6759$fn__6760.invoke(pedantic.clj:110)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:58)
	at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59)
	at clojure.lang.ChunkedCons.next(ChunkedCons.java:43)
	at clojure.lang.RT.next(RT.java:709)
	at clojure.core$next__5371.invokeStatic(core.clj:64)
	at clojure.core$dorun.invokeStatic(core.clj:3142)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clojure.core$doall.invoke(core.clj:3148)
	at leiningen.core.pedantic$all_paths.invokeStatic(pedantic.clj:113)
	at leiningen.core.pedantic$all_paths.invoke(pedantic.clj:100)
	at leiningen.core.pedantic$transform_graph.invokeStatic(pedantic.clj:123)
	at leiningen.core.pedantic$transform_graph.invoke(pedantic.clj:115)
	at leiningen.core.pedantic$use_transformer$reify__6787.transformGraph(pedantic.clj:161)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:275)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:307)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:102)
	at cemerick.pomegranate.aether$resolve_dependencies_STAR_.invokeStatic(aether.clj:806)
	at cemerick.pomegranate.aether$resolve_dependencies_STAR_.doInvoke(aether.clj:707)
```

**Comment by ejona86** [comment] 2022-04-19 15:14
@liuchong, did you add that comment to the wrong github issue? That error seems to have no relation with this issue.

**Comment by liuchong** [comment] 2022-04-19 15:19
Not sure, but my fail was also start from 2.0.48, I thinks should be related issue although the error message seems not.

**Comment by tanvp112** [comment] 2022-05-30 08:24
Tested 2.0.48 ~ to the latest with neo4j, all failed and it looks like dependencies error:
```
2022-05-30 08:19:36.838+0000 ERROR Failed to start Neo4j on 0.0.0.0:7474.
java.lang.RuntimeException: Error starting Neo4j database server at /data/databases
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:228) ~[neo4j-4.4.7.jar:4.4.7]
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:181) ~[neo4j-4.4.7.jar:4.4.7]
        at com.neo4j.server.enterprise.EnterpriseManagementServiceFactory.createManagementService(EnterpriseManagementServiceFactory.java:38) ~[neo4j-enterprise-4.4.7.jar:4.4.7]
        at com.neo4j.server.enterprise.EnterpriseBootstrapper.createNeo(EnterpriseBootstrapper.java:20) ~[neo4j-enterprise-4.4.7.jar:4.4.7]
        at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:142) [neo4j-4.4.7.jar:4.4.7]
        at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:95) [neo4j-4.4.7.jar:4.4.7]
        at com.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:24) [neo4j-enterprise-4.4.7.jar:4.4.7]
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.bolt.BoltServer@46fa2a7e' failed to initialize. Please see the attached cause exception "io.netty.internal.tcnative.SSLPrivateKeyMethod".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:424) ~[neo4j-common-4.4.7.jar:4.4.7]
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:65) ~[neo4j-common-4.4.7.jar:4.4.7]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:101) ~[neo4j-common-4.4.7.jar:4.4.7]
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:219) ~[neo4j-4.4.7.jar:4.4.7]
        ... 6 more
Caused by: java.lang.NoClassDefFoundError: io/netty/internal/tcnative/SSLPrivateKeyMethod
        at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:473) ~[netty-handler-4.1.75.Final.jar:4.1.75.Final]
        at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:606) ~[netty-handler-4.1.75.Final.jar:4.1.75.Final]
        at org.neo4j.ssl.SslPolicy.nettyServerContext(SslPolicy.java:82) ~[neo4j-ssl-4.4.7.jar:4.4.7]
        at org.neo4j.bolt.BoltServer.createSslContext(BoltServer.java:398) ~[neo4j-bolt-4.4.7.jar:4.4.7]
        at org.neo4j.bolt.BoltServer.createExternalProtocolInitializer(BoltServer.java:345) ~[neo4j-bolt-4.4.7.jar:4.4.7]
        at org.neo4j.bolt.BoltServer.init(BoltServer.java:202) ~[neo4j-bolt-4.4.7.jar:4.4.7]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:403) ~[neo4j-common-4.4.7.jar:4.4.7]
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:65) ~[neo4j-common-4.4.7.jar:4.4.7]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:101) ~[neo4j-common-4.4.7.jar:4.4.7]
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:219) ~[neo4j-4.4.7.jar:4.4.7]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSLPrivateKeyMethod
>>>>>
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
<<<<<
        at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:473) ~[netty-handler-4.1.75.Final.jar:4.1.75.Final]
        at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:606) ~[netty-handler-4.1.75.Final.jar:4.1.75.Final]
        at org.neo4j.ssl.SslPolicy.nettyServerContext(SslPolicy.java:82) ~[neo4j-ssl-4.4.7.jar:4.4.7]
        at org.neo4j.bolt.BoltServer.createSslContext(BoltServer.java:398) ~[neo4j-bolt-4.4.7.jar:4.4.7]
        at org.neo4j.bolt.BoltServer.createExternalProtocolInitializer(BoltServer.java:345) ~[neo4j-bolt-4.4.7.jar:4.4.7]
        at org.neo4j.bolt.BoltServer.init(BoltServer.java:202) ~[neo4j-bolt-4.4.7.jar:4.4.7]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:403) ~[neo4j-common-4.4.7.jar:4.4.7]
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:65) ~[neo4j-common-4.4.7.jar:4.4.7]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:101) ~[neo4j-common-4.4.7.jar:4.4.7]
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:219) ~[neo4j-4.4.7.jar:4.4.7]
        ... 6 more
```

Anyone with any idea is welcome... thanks!

**Comment by temawi** [comment] 2022-06-14 03:10
FYI - this issue is now mentioned on the [netty-tcnative site](https://netty.io/wiki/forked-tomcat-native.html). There is a "Gradle and Bazel" section that states:

> The maven packaging changed a bit in version 2.0.49.Final. The changes were fine for Maven users, but causes some trouble for Gradle and Bazel users. For Gradle, the solution is to explicitly declare the tcnative dependencies with classifiers. For Bazel, the solution is to use a Bazel version that contain this fix: https://github.com/bazelbuild/rules_jvm_external/pull/687

I have a working solution for grpc-java in https://github.com/grpc/grpc-java/pull/9027, but I still need to wait for a new Bazel build with the mentioned fix.

**Comment by KAITYOZHE** [comment] 2022-07-28 01:34
why netty-tcnative-boringssl-static-1.0.48   to   netty-tcnative-boringssl-static-1.0.49 is  problem ?
minor version Shouldn't A problem occurs.


java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
	at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:246) ~[grpc-netty-1.39.0.jar:1.39.0]
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146) ~[grpc-netty-1.39.0.jar:1.39.0]
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95) ~[grpc-netty-1.39.0.jar:1.39.0]

**Comment by snalli** [comment] 2023-01-05 19:33
Why does netty do this (all the time !) ?!!!

**Comment by normanmaurer** [comment] 2024-02-28 16:55
I think this should be fixed

**Closed by normanmaurer** 2024-02-28 16:55 UTC
