### ISSUE TITLE
SSL set mode support

### ISSUE THREAD

**Issue by tanersener** [netty/netty-tcnative#100] opened 2016-02-01 22:31 UTC
Hi,

Do you plan to support SSL_CTX_set_mode operation? In some cases enabling SSL_MODE_ENABLE_PARTIAL_WRITE and SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER modes is necessary but as you pointed out in https://github.com/netty/netty-tcnative/issues/81 SSLExt is not supported and there is not any other way to set them.

https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_set_mode.html

**Comment by Scottmitch** [comment] 2016-02-01 22:54
Are you using this library standalone or with Netty?

**Comment by tanersener** [comment] 2016-02-02 06:09
I'm using it with netty 4.0.x.

**Comment by normanmaurer** [comment] 2016-02-02 07:06
Can you tell us why you need to adjust these?

**Comment by tanersener** [comment] 2016-02-02 08:18
Well, my case is; I'm receiveing "error:1409F07F:SSL routines:SSL3_WRITE_PENDING: bad write retry" error on high load. After some google digging I found the following thread which suggests me to enable these flags. That's why I'm asking. 

http://stackoverflow.com/questions/2997218/why-am-i-getting-error1409f07fssl-routinesssl3-write-pending-bad-write-retr#

**Comment by normanmaurer** [comment] 2016-02-02 09:25
@tanersener this sound more like a netty bug. Can you share a reproducer or / and the full stack trace ?

**Comment by normanmaurer** [comment] 2016-02-02 13:25
@tanersener actually I think you are right and we need set `SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER` because if the user writes an heap-buffer the memoryAddress will most likely change between SSL_write(...) operations on retry. This is because in this case we will copy from heap to direct buffer before call SSL_write(...).

https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/OpenSslEngine.java#L287

Let me work on a fix for this.

**Comment by normanmaurer** [comment] 2016-02-02 18:03
@tanersener done via https://github.com/netty/netty-tcnative/pull/101. Will make use of this in netty once merged and released.

**Comment by tanersener** [comment] 2016-02-02 19:04
@normanmaurer you are very fast thanks. I just tested your pull request with commit from netty side locally and it worked for me. SSL_write error is gone. 
Any chance of backporting this feature to 4.0.x line?

**Comment by normanmaurer** [comment] 2016-02-02 19:07
@tanersener awesome!

Yes it will be applied to 4.0 and 4.1

**Comment by tanersener** [comment] 2016-02-02 19:11
@normanmaurer cool, thanks again

**Comment by normanmaurer** [comment] 2016-02-02 20:15
Fixed by https://github.com/netty/netty-tcnative/pull/101

**Closed by normanmaurer** 2016-02-02 20:15 UTC
Labels: feature
