### ISSUE TITLE
netty-tcnative not available for ppc64le on maven repository

### ISSUE THREAD

**Issue by npanpaliya** [netty/netty-tcnative#194] opened 2016-10-06 10:55 UTC
We want to port grpc-java on Power for which netty-tcnative jar built on Power is a pre-requisite.
Although I could build netty-tcnative on Power locally to satisfy the dependency of grpc-java, we would request to publish the jar for ppc64le platform too on maven's central repository. netty-tcnative does not have any porting issues on Power, so it should be easier.
Kindly let me know if any help is needed with respect to Power systems for building the jar.

**Comment by normanmaurer** [comment] 2016-12-20 13:01
@npanpaliya if we want to support it we would need to have access to systems which are ppc64le which is currently not the case.

**Comment by npanpaliya** [comment] 2016-12-20 14:45
@normanmaurer I'll get back to you tomorrow on this.

**Comment by npanpaliya** [comment] 2016-12-21 13:21
Hi @normanmaurer,

Could you please check this and try https://openpowerfoundation.org/blogs/openpower-cognitive-cup/?

**Comment by normanmaurer** [comment] 2016-12-21 14:30
@npanpaliya what you mean with trying ?

**Comment by npanpaliya** [comment] 2016-12-21 15:05
@normanmaurer , you could check this link. https://ptopenlab.com/cloudlabconsole/index.html. Here, he can register and then apply for VM and then you can use that VM to build netty-tcnative jar for ppc64le. I've not tried it myself but it works.

**Comment by npanpaliya** [comment] 2016-12-29 14:09
Hi @normanmaurer , did you get a chance to try this SuperVessel stuff to get Power VM?

**Comment by Scottmitch** [comment] 2016-12-30 21:14
I would recommend building the artifact locally in the mean time. I don't think this will happen near term. If there are any special changes/build steps necessary please list them here so we may be able to use them in the future, or anyone else using this platform can also reap the benefits.

**Comment by odaira** [comment] 2017-10-05 21:41
Hi, @normanmaurer 

I hit the same problem.  I can provide you with the binaries built on ppc64le, but I guess you would like to build them yourself, correct?

**Comment by normanmaurer** [comment] 2018-06-24 10:50
@odaira correct... the problem is we do not have any infrastructure to support this during our release process.

**Comment by normanmaurer** [comment] 2018-06-24 10:52
Closing as we do not have the infrastructure to support this

**Closed by normanmaurer** 2018-06-24 10:52 UTC
