### ISSUE TITLE
consider shading the org.tomcat classes

### ISSUE THREAD

**Issue by jorgheymans** [netty/netty-tcnative#214] opened 2016-12-22 13:55 UTC
I ran into an issue with a spring-boot enabled grpc server and TLS, using netty-tcnative-boringssl-static:1.1.33.Fork24. 

Basically the problem was that my project included the spring-boot-starter-web dependency, which brings in spring-boot-starter-tomcat, which depends on tomcat-embed-core.  And this jar contains the same tomcat/jni classes used in openssl-dynamic, causing things to break.

**Comment by Scottmitch** [comment] 2016-12-27 17:17
This is a duplicate of https://github.com/netty/netty-tcnative/issues/136.

We have re-namespaced netty-tcnative into a different package on the `master` branch. This change will take effect in `netty-tcnative-2.0.0` and the next release of Netty should depend upon this new `netty-tcnative`.

**Closed by Scottmitch** 2016-12-27 17:17 UTC
